name = "ArrayIterators"
uuid = "3a1e593a-8d3c-11e9-3b79-993a9d31f8cc"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "0.1.0"

[compat]
julia = ">= 1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
